#!/usr/bin/env bash
# villa.solay.cloud — one-time VPS setup. Run ONCE, from the Mac:
#
#   ssh ibukadek-vps 'bash -s' < scripts/vps-bootstrap.sh
#
# Sets up the bare repo that scripts/deploy.sh pushes to, the hook that checks
# it out, the data directories, and a starter .env (secrets generated, people
# passwords left for a human). Idempotent — safe to run again; never touches
# an existing .env.

set -euo pipefail

REPO=/opt/villa.git
WORKTREE=/opt/villa
ENV_FILE="$WORKTREE/.env"

echo "== villa.solay.cloud VPS bootstrap =="

# --- bare repo --------------------------------------------------------------
if [ -d "$REPO" ]; then
  echo "bare repo already exists: $REPO"
else
  git init --bare "$REPO" >/dev/null
  echo "created bare repo: $REPO"
fi

mkdir -p "$WORKTREE"

# --- post-receive hook: checkout master into the worktree -------------------
cat > "$REPO/hooks/post-receive" <<'HOOK'
#!/usr/bin/env bash
set -euo pipefail
git --work-tree=/opt/villa --git-dir=/opt/villa.git checkout -f master
echo "[post-receive] checked out master into /opt/villa"
HOOK
chmod +x "$REPO/hooks/post-receive"
echo "post-receive hook installed (checks out master into $WORKTREE on every push)"

# --- data directories ---------------------------------------------------------
mkdir -p "$WORKTREE/data/images" "$WORKTREE/data/cache" "$WORKTREE/data/backups"
chown -R 1000:1000 "$WORKTREE/data"   # the container runs as uid 1000 (node), see Dockerfile
echo "data dirs ready: $WORKTREE/data/{images,cache,backups}"

# --- .env --------------------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists — leaving it alone"
else
  SESSION_SECRET=$(openssl rand -hex 32)
  ADMIN_TOKEN=$(openssl rand -hex 32)
  AGENT_TOKEN=$(openssl rand -hex 32)

  cat > "$ENV_FILE" <<ENVEOF
# villa.solay.cloud — generated by vps-bootstrap.sh on $(date -u +%F). Never commit this file.
# Mirrors .env.example; see that file in the repo for what each key does.

SESSION_SECRET=$SESSION_SECRET
ADMIN_TOKEN=$ADMIN_TOKEN
AGENT_TOKEN=$AGENT_TOKEN

# *** SET THESE — no password was invented. Fill in real values by hand. ***
USER1_EMAIL=philipp.solay@gmail.com
USER1_NAME=Philipp
USER1_PASSWORD=SET-THIS-a-long-passphrase
USER2_EMAIL=abigail@example.com
USER2_NAME=Abigaïl
USER2_PASSWORD=SET-THIS-a-long-passphrase

TZ=Asia/Makassar
SCRAPE_CRON=0 6 * * *
PLAYWRIGHT=0

# Contact address Nominatim asks for when geocoding pins.
NOMINATIM_EMAIL=philipp.solay@gmail.com

# Optional: enables the LLM-assisted feedback parsing in \`learn\`. Leave empty to stay rule-based.
ANTHROPIC_API_KEY=

# Matches the existing Traefik setup on this VPS (see the traefik-traefik-1 container).
TRAEFIK_NETWORK=proxy
TRAEFIK_CERTRESOLVER=mytlschallenge
ENVEOF
  echo "wrote $ENV_FILE — generated SESSION_SECRET, ADMIN_TOKEN, AGENT_TOKEN"
fi

chmod 600 "$ENV_FILE"

echo
echo "== done =="
echo "still needs a human:"
echo "  nano $ENV_FILE     # set USER1_PASSWORD and USER2_PASSWORD (and check the emails/names)"
echo
echo "then, from the Mac:"
echo "  scripts/deploy.sh --data   # first deploy: pushes code, syncs data, builds, starts"
